services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "80:80"
    redis:
        image: redis:latest
        volumes:
            - redis_data:/data
volumes:
  redis_data:
